/* AUTOGENERATED FILE. DO NOT EDIT. */
#include "unity.h"
#include "Exception.h"
#include <setjmp.h>

jmp_buf AbortFrame;

extern void setUp(void);
extern void tearDown(void);

extern void test_BasicTryDoesNothingIfNoThrow(void);
extern void test_BasicThrowAndCatch(void);
extern void test_VerifyVolatilesSurviveThrowAndCatch(void);
extern void test_ThrowFromASubFunctionAndCatchInRootFunc(void);
extern void test_ThrowAndCatchFromASubFunctionAndRethrowToCatchInRootFunc(void);
extern void test_ThrowAndCatchFromASubFunctionAndNoRethrowToCatchInRootFunc(void);
extern void test_CanHaveMultipleTryBlocksInASingleFunction(void);
extern void test_CanHaveNestedTryBlocksInASingleFunction_ThrowInside(void);
extern void test_CanHaveNestedTryBlocksInASingleFunction_ThrowOutside(void);
extern void test_CanThrowADetailedExceptionAndCheckOutTheResults(void);

static void runTest(UnityTestFunction test)
{
  if (setjmp(AbortFrame) == 0)
  {
    setUp();
    Try
    {
      test();
    }
    Catch
    {
      TEST_FAIL("Unexpected exception!")
    }
  }
  tearDown();
}


int main(void)
{
  Unity.TestFile = __FILE__;
  UnityBegin();

  // RUN_TEST calls runTest
  RUN_TEST(test_BasicTryDoesNothingIfNoThrow);
  RUN_TEST(test_BasicThrowAndCatch);
  RUN_TEST(test_VerifyVolatilesSurviveThrowAndCatch);
  RUN_TEST(test_ThrowFromASubFunctionAndCatchInRootFunc);
  RUN_TEST(test_ThrowAndCatchFromASubFunctionAndRethrowToCatchInRootFunc);
  RUN_TEST(test_ThrowAndCatchFromASubFunctionAndNoRethrowToCatchInRootFunc);
  RUN_TEST(test_CanHaveMultipleTryBlocksInASingleFunction);
  RUN_TEST(test_CanHaveNestedTryBlocksInASingleFunction_ThrowInside);
  RUN_TEST(test_CanHaveNestedTryBlocksInASingleFunction_ThrowOutside);
  RUN_TEST(test_CanThrowADetailedExceptionAndCheckOutTheResults);

  UnityEnd();
  
  return 0;
}
